### ISSUE TITLE
Enhancement request: Make search bar wider

### ISSUE THREAD

**Issue by amandafrench** [ror-community/ror-app#164]
We've had a request via the support account to make the search bar wider on https://ror.org/search.

**Comment by lizkrznarich** [comment]
@amandafrench Could you please file this in https://github.com/ror-community/ror-roadmap/issues as a feature request? It gets a little unwieldy to keep track of all the issues when they are attached to separate repositories.

**Comment by amandafrench** [comment]
Ah, yes, right, sorry, will do

**Comment by amandafrench** [comment]
Moved to https://github.com/ror-community/ror-roadmap/issues/141
