### ISSUE TITLE
Show a better web-page for an invalid ROR IDs

### ISSUE THREAD

**Issue by paulmillar** [ror-community/ror-app#52]
If I put a ROR ID in my web-browser, I see a short summary of information about that institute; e.g., https://ror.org/01js2sh04.  This is good.

If I put an incorrect ID into my web-browser, then I see only a blank page; e.g,. https://ror.org/0-no-such-ID.  This is bad.

It would be better if the page for an invalid ROR ID included some clear indication to the user that the ID was invalid.  The page might also provide some links that could allow a user to recover from this situation (e.g,. link to the ROR main page, link to the search facility, etc).

On a technical level, the server should probably return a `404` status code.  This would allow automated scripts to understand the nature of the problem.  Currently the server returns a status code of  `200`, which indicates that there was no problem.

**Comment by lizkrznarich** [comment]
Hi @paulmillar, apologies for the delay following up on this. This was fixed as part of https://github.com/ror-community/ror-app/pull/83 . The API and UI message for cases like https://ror.org/0-no-such-ID is 'ror.org/0-no-such-ID' is not a valid ROR ID.
